In [103]:
from sklearn.mixture import GaussianMixture
import numpy as np


random_data = np.random.rand(100,2)
random_data2 = np.random.rand(100,2)
random_data3 = np.random.rand(100,2)

gmm1 = GaussianMixture(n_components=5)
gmm1.fit(random_data)

gmm2 = GaussianMixture(n_components=7)
gmm2.fit(random_data)

gmm3 = GaussianMixture(n_components=3)
gmm3.fit(random_data)

GaussianMixture(n_components=3)

In [104]:
# Sample from the first GMM

sampled_data, _ = gmm1.sample(10)

In [105]:
score_1 = gmm1.score_samples(sampled_data)
score_2 = gmm2.score_samples(sampled_data)
score_3 = gmm3.score_samples(sampled_data)

In [106]:
import torch

log_probs = torch.stack([torch.tensor(score_1), torch.tensor(score_2), torch.tensor(score_3)], dim=1)

In [107]:
log_probs

tensor([[-0.2860, -0.7751,  0.0770],
        [ 0.6041,  0.2814,  0.7434],
        [ 0.3998,  0.5042, -0.2014],
        [-1.2192, -1.2638, -0.6967],
        [ 0.1633, -0.2137, -0.1894],
        [ 0.3716,  0.4781,  0.0983],
        [-0.2341,  0.3182, -0.2804],
        [-0.7428, -0.5180, -0.2786],
        [-0.9438, -0.7164, -0.9481],
        [ 0.2204,  0.3125,  0.5140]], dtype=torch.float64)

In [108]:
proportions = (log_probs[:, 0].unsqueeze(1) < log_probs).float().mean(dim=0)

In [119]:
(log_probs.max(dim=1).indices == 0).float().mean()

tensor(0.1000)

In [109]:
proportions

tensor([0.0000, 0.6000, 0.5000])

In [110]:
log_probs[:, 0].unsqueeze(1) < log_probs

tensor([[False, False,  True],
        [False, False,  True],
        [False,  True, False],
        [False, False,  True],
        [False, False, False],
        [False,  True, False],
        [False,  True, False],
        [False,  True,  True],
        [False,  True, False],
        [False,  True,  True]])